### ISSUE TITLE
Unable to use SELECT query without where condition.

### ISSUE THREAD

**Issue by techie-nikhil** [salunkhe-ravi/noompy#6]
When we try to execute SELECT query without where condition to get whole sheet, it returns message like "WHERE clause did not retrieve any matching result.".

Code I used :-
noom1 = NoomPy(excel_path='path_of_file.xlsx')
res = noom1.select_data(select_query="SELECT * FROM TestScenarios")
print(res)

Output :- WHERE clause did not retrieve any matching result.

**Comment by salunkhe-ravi** [comment]
Hello @nikhilmymail101 ,

That's an expected behavior if no "where" clause is provided. Again, the user should provide a where statement to get the necessary output from the file.
Any specific use case are you looking at?

**Comment by techie-nikhil** [comment]
Hi @salunkhe-ravi ,

I want to update a sheet by using update query of fillo library of java from one project and use the same sheet in another project created on python.
In python project I want to get all the rows and columns of specific sheet and by using the query (select_query="SELECT * FROM TestScenarios").
when I use this, it shows "WHERE clause did not retrieve any matching result." as output.

I am able to use same query in fillo.

**Comment by salunkhe-ravi** [comment]
Ok...
We may need to raise this as a feature request then..

**Comment by salunkhe-ravi** [comment]
Hello @nikhilmymail101 ,

Please raise a feature request if you want us to support your requirement.
If not, maybe can then close this issue.

**Comment by salunkhe-ravi** [comment]
@nikhilmymail101 - Closing this one due to no response.
